    compute_permutation=False,                                [0/2197]
  File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-pa
ckages/pb_bss_eval/evaluation/module_mir_eval.py", line 68, in mir_eva
l_sources                                                             
    for d in range(reference.shape[1])                                
  File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-pa
ckages/pb_bss_eval/evaluation/module_mir_eval.py", line 68, in <listco
mp>                                                                   
    for d in range(reference.shape[1])                                
  File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-pa
ckages/pb_bss_eval/evaluation/module_mir_eval.py", line 44, in mir_eva
l_sources                                                             
    compute_permutation=compute_permutation                           
  File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-pa
ckages/mir_eval/separation.py", line 194, in bss_eval_sources             validate(reference_sources, estimated_sources)                    
  File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-packages/mir_eval/separation.py", line 94, in validate                      raise ValueError('All the reference sources should be non-silent (
not '                                                                 ValueError: All the reference sources should be non-silent (not all-zeros), but at least one of the reference sources is all 0s, which introduces ambiguity to the evaluation. (Otherwise we can add infinitely many all-zero sources.)                                                                                                                       The above exception was the direct cause of the following exception:                                                                        Traceback (most recent call last):                                      File "test.py", line 215, in <module>                                   main(arg_dic)                                                       File "test.py", line 137, in main                                       metrics_list=COMPUTE_METRICS,                                       File "/mnt/sda1/nicolas/miniconda3/envs/thesis/lib/python3.7/site-packages/asteroid/metrics.py", line 111, in get_metrics                     ) from err                                                        RuntimeError: Error computing input_sdr for <unknown file>
